{
 "title": "Prometheus Flask exporter example dashboard",
 "description": "Example dashboard for monitoring Flask webapps using prometheus_flask_exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\"}[$__rate_interval])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  }
 ]
}